const actions = { 
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    PRODUCTS_FETCHED: "PRODUCTS_FETCHED",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART"
};

export default actions;