const actions = { 
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    PRODUCTS_FETCHED: "PRODUCTS_FETCHED",

    GET_SEARCH_LIST: "GET_SEARCH_LIST",
    SEARCH_LIST_FETCHED: "SEARCH_LIST_FETCHED",

    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    
    SET_CUR_USER: "SET_CUR_USER"
};

export default actions;